# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy current directory contents into the container at /app
COPY . /app

# Run the Python script
CMD ["python", "app.py"]
