name: Fetch PR Comments on Merge

on:
  push:
    branches:
      - main

jobs:
  fetch-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the merged pull request number
        id: get_pr
        run: |
          # Fetch the commit SHA that triggered the action
          COMMIT_SHA=$(echo "${GITHUB_SHA}")
          
          # Get the PR number associated with this commit
          PR_NUMBER=$(gh pr list --state merged --json number,headRefName,baseRefName --jq ".[] | select(.headRefName==\"$GITHUB_REF\") | .number")
          
          # Check if we found a PR number
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR associated with this commit."
            exit 1
          fi
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV

      - name: Fetch PR Comments
        id: fetch_comments
        run: |
          # Fetch the comments from the PR
          COMMENTS=$(gh pr view ${{ env.PR_NUMBER }} --json comments --jq '.comments[].body' | tr '\n' ';')
          echo "COMMENTS=${COMMENTS}" >> $GITHUB_ENV

      - name: Run Python Script
        run: |
          echo "${{ env.COMMENTS }}" > comments.txt
          python3 your_script.py comments.txt
