name: Get PR from Commit SHA

on:
  push:
    branches:
      - main

jobs:
  get-pr-from-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR number from commit SHA
        id: get-pr
        uses: actions/github-script@v6
        with:
          script: |
            const sha = process.env.GITHUB_SHA; // Get the current commit SHA
            const { data: pullRequests } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
            });

            if (pullRequests.length === 0) {
              throw new Error(`No pull requests associated with commit SHA ${sha}`);
            }

            // Take the first PR in case there are multiple
            const prNumber = pullRequests[0].number;
            console.log(`PR number: ${prNumber}`);
            return { prNumber };

      - name: Print PR number
        run: echo "PR number is ${{ steps.get-pr.outputs.prNumber }}"
