name: Get PR Comment and Run Python Script

on:
  push:
    branches:
      - main

jobs:
  get-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR number from commit SHA
        id: get-pr
        uses: actions/github-script@v6
        with:
          script: |
            const sha = process.env.GITHUB_SHA; // Get the current commit SHA
            const { data: pullRequests } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
            });

            if (pullRequests.length === 0) {
              throw new Error(`No pull requests associated with commit SHA ${sha}`);
            }

            // Take the first PR in case there are multiple
            const prNumber = pullRequests[0].number;
            console.log(`Found PR number: ${prNumber}`);
            return { prNumber };

      - name: Set PR number as output
        run: echo "PR_NUMBER=${{ steps.get-pr.outputs.prNumber }}" >> $GITHUB_ENV

      - name: Get latest comment from GitHub Actions bot
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = process.env.PR_NUMBER; // Get the PR number from the environment variable
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            // Filter comments by github-actions bot
            const botComments = comments.filter(comment => comment.user.login === 'github-actions[bot]');

            if (botComments.length === 0) {
              throw new Error('No comments found from GitHub Actions bot.');
            }

            // Get the most recent comment
            const latestComment = botComments[botComments.length - 1].body;
            console.log(`Latest comment: ${latestComment}`);
            return { latestComment };

      - name: Set latest comment as output
        run: echo "LATEST_COMMENT=${{ steps.get-latest-comment.outputs.latestComment }}" >> $GITHUB_ENV

      - name: Run Python script with the comment
        run: python3 .github/scripts/parse_new_versions.py
        env:
          LATEST_COMMENT: ${{ env.LATEST_COMMENT }}

      - name: Print comment from Python script
        run: |
          python3 -c "
          import os
          comment = os.getenv('LATEST_COMMENT')
          print(f'The latest comment by github-actions bot: {comment}')
          "
