name: Detect Modified Steps
on:
  pull_request:
    branches: [ main ]
jobs:
  check-modified-folders:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find modified folders
        id: modified_folders
        run: |
          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            git fetch --prune --unshallow
          fi
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            BASE=HEAD^
          else
            BASE=$(git hash-object -t tree /dev/null)
          fi
          MODIFIED_FOLDERS=$(git diff --name-only $BASE HEAD flows/steps/ | cut -d'/' -f3 | sort | uniq)
          
           # Join the modified folder names into a single space-separated string
          MODIFIED_FOLDERS_JOINED=$(echo "$MODIFIED_FOLDERS" | tr '\n' ' ')

          # Print the modified files for debugging
          echo "DEBUG: Modified files: $(git diff --name-only $BASE HEAD flows/steps/)"
          echo "DEBUG: Extracted folder names: $MODIFIED_FOLDERS"

          # Print the modified folders
          echo "Modified step folders: $MODIFIED_FOLDERS_JOINED"

          # Save the modified folders as output for use in other steps
          echo "::set-output name=folders::$MODIFIED_FOLDERS_JOINED"

      - name: Create Comment
        if: steps.modified_folders.outputs.changes != '[]'
        run: |
          # Use GitHub API to create a comment on the PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="Your checklist comment here \n ${{ steps.modified_folders.outputs.folders }}"
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
      
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
