name: Get PR Comment and Run Python Script

on:
  push:
    branches:
      - main

permissions:
  contents: write    # This is required for pushing tags
  pull-requests: read  # If you need to read PR information

jobs:
  get-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR number from commit SHA
        id: get-pr
        uses: actions/github-script@v6
        with:
          script: |
            const sha = process.env.GITHUB_SHA; // Get the current commit SHA
            const { data: pullRequests } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
            });

            if (pullRequests.length === 0) {
              throw new Error(`No pull requests associated with commit SHA ${sha}`);
            }

            // Take the first PR in case there are multiple
            const prNumber = pullRequests[0].number;
            console.log(`Found PR number: ${prNumber}`);
            // Set the PR number as an environment variable
            console.log(`PR_NUMBER=${prNumber}`); // Debug log
            core.exportVariable('PR_NUMBER', prNumber);

      - name: Get latest comment from GitHub Actions bot
        uses: actions/github-script@v6
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}  # Passing the PR number as env variable
        with:
          script: |
            const prNumber = process.env.PR_NUMBER; // Get the PR number from the environment variable
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            // Filter comments by github-actions bot
            const botComments = comments.filter(comment => comment.user.login === 'github-actions[bot]');

            if (botComments.length === 0) {
              throw new Error('No comments found from GitHub Actions bot.');
            }

            // Get the most recent comment
            const latestComment = botComments[botComments.length - 1].body;
            console.log(`Latest comment: ${latestComment}`);
            core.exportVariable('LATEST_COMMENT', latestComment);


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver

      - name: Extract Versions from the PR bot comment
        id: extract-versions
        run: |
          python .github/scripts/parse_new_version.py 
        env:
          LATEST_COMMENT: ${{ env.LATEST_COMMENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      
          