name: detect-modified-steps

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'flows/steps/**'

jobs:
  check-modified-folders:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find modified folders
        id: modified-folders
        run: |
          # Fetch the modified folders between the base and head commits
          MODIFIED_FOLDERS=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} flows/steps/ | cut -d'/' -f3 | sort | uniq | grep -v '^$' || true)
          
          echo "DEBUG: Raw MODIFIED_FOLDERS content:"
          echo "$MODIFIED_FOLDERS"

          # If no modified folders are found, set an empty list and exit
          if [ -z "$MODIFIED_FOLDERS" ]; then
            echo "folders=[]" >> $GITHUB_OUTPUT
            echo "No modified folders found"
            exit 0
          fi

          # Convert the list of folders (with newlines) into a JSON array
          FOLDERS_JSON=$(echo "$MODIFIED_FOLDERS" | jq -R . | jq -s . | jq -c .)
          
          # Output the folders as JSON to GitHub Actions output
          echo "folders=${FOLDERS_JSON}" >> $GITHUB_OUTPUT
          echo "DEBUG: Modified folders: ${FOLDERS_JSON}"




      - name: Set up Python
        if: fromJSON(steps.modified-folders.outputs.folders) != '[]'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        if: fromJSON(steps.modified-folders.outputs.folders) != '[]'
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Process Docker tags
        if: fromJSON(steps.modified-folders.outputs.folders) != '[]'
        id: docker-tags
        run: |
          # Run Python script and capture output
          TAGS_OUTPUT=$(python .github/scripts/docker_tags.py \
            '${{ steps.modified-folders.outputs.folders }}' \
            '${{ secrets.DOCKER_USER }}' \
            '${{ secrets.DOCKER_PWD }}')
          
          # Save output to GITHUB_OUTPUT
          echo "tags=$TAGS_OUTPUT" >> $GITHUB_OUTPUT
          echo "DEBUG: Tags output: $TAGS_OUTPUT"

      - name: Create PR Comment
        if: fromJSON(steps.modified-folders.outputs.folders) != '[]'
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const folders = ${{ steps.modified-folders.outputs.folders }};
              const tags = ${{ steps.docker-tags.outputs.tags || '[]' }};
              
              let comment = '## Modified Steps Check\n\n';
              
              // Add folders section
              comment += '### Modified Folders:\n';
              if (folders && folders.length > 0) {
                folders.forEach(folder => {
                  comment += `- \`${folder}\`\n`;
                });
              } else {
                comment += '_No modified folders found_\n';
              }
              
              // Add tags section
              comment += '\n### Image Version Bump Info:\n';
              comment += '\n#### Edit this comment to update the new version for each image within the [ ]:\n';
              if (tags && tags.length > 0) {
                tags.forEach(([step, currentTag]) => {
                  // Calculate the next patch version
                  const [major, minor, patch] = currentTag.split('.').map(Number);
                  const nextPatchVersion = `${major}.${minor}.${patch + 1}`;
                  
                  // Format the output
                  comment += `- \`${step}\` | [${currentTag}] -> [${nextPatchVersion}]\n` |;
                });
              } else {
                comment += '_No matching tags found_\n';
              }
              
              comment += '\n⚠️ Please review these changes carefully before merging. ';
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            } catch (error) {
              core.setFailed(`Action failed with error: ${error}`);
              console.log('Error details:', error);
            }
